name: drum_ice
description: Drum Ice - Heladería artesanal. Inspirada en Drum Island de One Piece.
publish_to: 'none'
version: 1.0.8+9

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # SEO para Flutter Web
  seo: ^0.0.10

  # Tipografía Bree Serif
  google_fonts: ^6.2.1

  # Abrir WhatsApp
  url_launcher: ^6.3.1
  firebase_core: ^4.10.0
  quarks_footer:
    git:
      url: https://github.com/Quarks-Studio/quarks_footer.git
      ref: v1.2.0
  quarks_version_checker:
    git:
      url: https://github.com/quarks-studio/quarks_version_checker
      ref: v1.1.0
  font_awesome_flutter: ^11.0.0
  firebase_analytics: ^12.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "assets/images/hero.png"
  web:
    generate: true
    image_path: "assets/images/hero.png"
    background_color: "#FFFFFF"
    theme_color: "#FFAECF"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
